version: "3"
services:
  agents-python-server:
    build:
      context: .
      dockerfile: dockerfile.agents-python-server
      args:
        OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
    restart: always
    volumes:
      # persist assets so they are not lost when the container is rebuilt
      - agents-assets:/agents-assets/

    networks:
      - agents-network
    
    logging:
      driver: fluentd
      options:
        fluentd-address: 34.133.235.56:443
        tag: defog.local.python-server

  agents-partykit:
    build:
      context: .
      dockerfile: dockerfile.agents-partykit
    networks:
      - agents-network
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: 34.133.235.56:443
        tag: defog.local.partykit

  agents-postgres:
    build:
      context: .
      dockerfile: dockerfile.agents-postgres
    networks:
      - agents-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - agents-postgres:/var/lib/postgresql/data

  agents-redis:
    build:
      context: .
      dockerfile: dockerfile.agents-redis
    networks:
      - agents-network
    volumes:
      - agents-redis:/data
  
  agents-nginx:
    build:
      context: .
      dockerfile: dockerfile.agents-nginx
      args:
        ENDPOINT: "${ENDPOINT}"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - agents-python-server
    networks:
      - agents-network
    
    logging:
      driver: fluentd
      options:
        fluentd-address: 34.133.235.56:443
        tag: defog.local.nginx

volumes:
  agents-postgres:
  agents-redis:
  agents-assets:

networks:
  agents-network:
