version: "3"
services:
  # run the cloud function in the docker for easier testing
  agents-llm-calls:
    build:
      context: .
      dockerfile: dockerfile.agents-llm-calls
    networks:
      - agents-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  agents-partykit:
    build:
      context: .
      dockerfile: dockerfile.agents-partykit
    networks:
      - agents-network
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: 34.133.235.56:443
        tag: defog.local.partykit

  agents-postgres:
    build:
      context: .
      dockerfile: dockerfile.agents-postgres
    networks:
      - agents-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - agents-postgres:/var/lib/postgresql/data

  agents-python-server:
    environment:
      - DEFOG_API_KEY=${DEFOG_API_KEY}
      - DEFOG_BASE_URL=${DEFOG_BASE_URL:-https://api.defog.ai}
      - DEFOG_GENERATE_URL=${DEFOG_GENERATE_URL:-https://api.defog.ai/generate_query_chat}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REPORT_ASSETS_DIR=${REPORT_ASSETS_DIR}
      - DBNAME=${DBNAME}
      - HOST=${HOST}
      - PORT=${PORT}
      - DATABASE=${DATABASE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - LLM_CALLS_URL=${LLM_CALLS_URL}
    build:
      context: .
      dockerfile: dockerfile.agents-python-server
      args:
        OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
    restart: always
    volumes:
      - agents-assets:/agents-assets/
    depends_on:
      - agents-partykit
      - agents-postgres

    networks:
      - agents-network

    logging:
      driver: fluentd
      options:
        fluentd-address: 34.133.235.56:443
        tag: defog.local.python-server

  agents-nginx:
    build:
      context: .
      dockerfile: dockerfile.agents-nginx
      args:
        ENDPOINT: "${ENDPOINT}"
        DEFOG_API_KEY: "${DEFOG_API_KEY}"
        GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
        PORT: "${PORT:-80}"
        BUTTON_TEXT: "${BUTTON_TEXT}"
        ALLOW_UPDATES: "${ALLOW_UPDATES:-YES}"
        ALLOW_CACHING: "${ALLOW_CACHING:-YES}"
    ports:
      - "${PORT:-80}:80"
      - "443:443"
    depends_on:
      - agents-python-server
    networks:
      - agents-network

    logging:
      driver: fluentd
      options:
        fluentd-address: 34.133.235.56:443
        tag: defog.local.nginx

volumes:
  agents-postgres:
  agents-assets:

networks:
  agents-network:
# curl --header "Content-Type: application/json"  --data '{"request_type": "ping"}' http://localhost:80/llm-calls/
