version: "3"
services:
  agents-app:
    build:
      context: .
      dockerfile: dockerfile.agents-app
    ports:
      # use a weird port to avoid conflicts with the user's local stuff
      - "1234:1234"
    networks:
      - agents-network

  agents-python-server:
    build:
      context: .
      dockerfile: dockerfile.agents-python-server
      args:
        GOOGLE_APPLICATION_CREDENTIALS_PATH: "${GOOGLE_APPLICATION_CREDENTIALS_PATH:?Please set the GOOGLE_APPLICATION_CREDENTIALS_PATH variable to the path of your service account credentials file.}"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /cloud-storage-creds.json
    # volumes:
    # - agents-python-server:/agents-python-server/
    ports:
      # we have to expose these ports to allow the browser to acces them
      # python server
      - "1235:1235"

    networks:
      - agents-network

  agents-partykit:
    build:
      context: .
      dockerfile: dockerfile.agents-partykit
    ports:
      # partykit
      - "1999:1999"
      # partykit also for nginx redirect
      - "2000:2000"
    expose:
      - "1999"
      - "2000"
    networks:
      - agents-network

  agents-rabbitmq:
    build:
      context: .
      dockerfile: dockerfile.agents-rabbitmq
      args:
        GOOGLE_APPLICATION_CREDENTIALS_PATH: "${GOOGLE_APPLICATION_CREDENTIALS_PATH:?Please set the GOOGLE_APPLICATION_CREDENTIALS_PATH variable to the path of your service account credentials file.}"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /cloud-storage-creds.json
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    networks:
      - agents-network

  agents-postgres:
    build:
      context: .
      dockerfile: dockerfile.agents-postgres
    networks:
      - agents-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - agents-postgres:/var/lib/postgresql/data

  agents-redis:
    build:
      context: .
      dockerfile: dockerfile.agents-redis
    networks:
      - agents-network
    volumes:
      - agents-redis:/data

volumes:
  agents-postgres:
  agents-redis:

networks:
  agents-network:
