version: "3.8"
services:
  agents-postgres:
    build:
      context: .
      dockerfile: dockerfile.agents-postgres
      platforms:
        - linux/amd64
        - linux/arm64

  agents-python-server:
    build:
      context: .
      dockerfile: dockerfile.agents-python-server-export
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        OPENAI_API_KEY: "${OPENAI_API_KEY:-}"

  agents-nginx:
    build:
      context: .
      dockerfile: dockerfile.agents-nginx
      platforms:
        - linux/amd64
        - linux/arm64

