version: "3"
services:
  agents-postgres:
    build:
      context: .
      dockerfile: dockerfile.agents-postgres
    networks:
      - agents-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - agents-postgres:/var/lib/postgresql/data

  agents-python-server:
    environment:
      - DEFOG_API_KEY=${DEFOG_API_KEY}
      - DEFOG_API_KEY_NAMES=${DEFOG_API_KEY_NAMES}
      - DEFOG_BASE_URL=${DEFOG_BASE_URL:-https://api.defog.ai}
      - DEFOG_GENERATE_URL=${DEFOG_GENERATE_URL:-https://api.defog.ai/generate_query_chat}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANALYSIS_ASSETS_DIR=${ANALYSIS_ASSETS_DIR}
      - DBNAME=${DEFOG_DBNAME:-postgres}
      - DBHOST=${DEFOG_DBHOST:-agents-postgres}
      - DBPORT=${DEFOG_DBPORT:-5432}
      - DATABASE=${DEFOG_DATABASE:-postgres}
      - DBUSER=${DEFOG_DBUSER:-postgres}
      - DBPASSWORD=${DEFOG_DBPASSWORD:-postgres}
      - REDIS_INTERNAL_PORT=${REDIS_INTERNAL_PORT}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LLM_CALLS_URL=${LLM_CALLS_URL}
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONPATH=/backend
      - INTERNAL_DB=${INTERNAL_DB:-postgres}
      - LLM_SERVER_ENDPOINT=${LLM_SERVER_ENDPOINT}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - STRIPE_ACCOUNT_ID=${STRIPE_ACCOUNT_ID}
      - STRIPE_CLIENT_SECRET=${STRIPE_CLIENT_SECRET}

      # Email configuration
      - EMAIL_OPTION=${EMAIL_OPTION:-DEFOG}
      - FROM_EMAIL=${FROM_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DELETE_EXISTING_TOOLS=${DELETE_EXISTING_TOOLS:-no}
    build:
      context: .
      dockerfile: dockerfile.agents-python-server
      args:
        OPENAI_API_KEY: "${OPENAI_API_KEY:-}"
    restart: always
    ports:
      - "1235:1235"
    volumes:
      - agents-assets:/agents-assets/
      - ./backend:/backend
    depends_on:
      - agents-postgres
      - agents-redis

    networks:
      - agents-network

  agents-nginx:
    build:
      context: .
      dockerfile: dockerfile.agents-nginx
    ports:
      - "${PORT:-80}:80"
      - "443:443"
    depends_on:
      - agents-python-server
    networks:
      - agents-network

  agents-redis:
    image: redis:7-alpine
    networks:
      - agents-network
    ports:
      - "${REDIS_EXTERNAL_PORT}:${REDIS_INTERNAL_PORT}"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
    command: >
      redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    environment:
      - REDIS_MAXMEMORY=256mb

volumes:
  agents-postgres:
  agents-assets:
  redis-data:

networks:
  agents-network: 
