name: Frontent Checks

on:
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  checks:
    name: Frontend Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.github }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        working-directory: ./frontend
        run: pnpm install --no-strict-peer-dependencies

      - name: Type Check
        working-directory: ./frontend
        run: pnpm exec tsc --noEmit

      - name: Export Check
        working-directory: ./frontend
        run: pnpm run test-pr-export
